id: P001841
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:25:10.563172
source_metadata:
  id: bdr:W1KG3173
  title: དཔལ་འབྲུག་པ་རིན་པོ་ཆེ་ངག་དབང་རྣམ་རྒྱལ་གྱི་རྣམ་ཐར་རྒྱ་མཚོའི་སྙིང་པོ་བསྡུས་པ།
  author: ''
  volumes:
    e3fe46f506734981bb51a6deb0a1d5ac:
      image_group_id: I1KG3209
      title: ''
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
