id: I2CFAA5CC
legacy_id: P001841
ocr_import_info:
  bdrc_scan_id: W1KG3173
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T11:34:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:56:41.629729+00:00'
last_modified: 2022-08-31 22:56:49.843657
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3173
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3173
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་འབྲུག་པ་རིན་པོ་ཆེ་ངག་དབང་རྣམ་རྒྱལ་གྱི་རྣམ་ཐར་རྒྱ་མཚོའི་སྙིང་པོ་བསྡུས་པ།
  author: འབྲུག་རྗེ་མཁན་པོ ༦༩་དགེ་འདུན་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.8338593219850351
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1KG3209:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3209
      total_pages: 248
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3209.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8338593219850351
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
